version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    command: node server.js
    volumes:
      - ./backend:/usr/src/app
      - ./data:/data       # mount your CSVs here (drivers.csv, orders.csv, routes.csv)
    environment:
      - MONGO_URI=mongodb://mongo:27017/greencart
      - JWT_SECRET=change_this_secret
      - ADMIN_USER=manager
      - ADMIN_PASS=managerpass
      - CSV_BASE_PATH=/data
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - VITE_API_BASE=http://localhost:5000
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]
volumes:
  mongo-data:
