name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # change if your default branch is not "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd GreenCart-Frontend
          npm install

      - name: Build React app
        run: |
          cd GreenCart-Frontend
          npm run build
          touch build/.nojekyll   # 🚀 ensures Jekyll is disabled

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./GreenCart-Frontend/build
